application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /head\.jpg
  static_files: head.jpg
  upload: head\.jpg

- url: /wsu\.png
  static_files: wsu.png
  upload: wsu\.png

- url: /rest/.*
  script: main.APP

- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app
